# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://smc.sourceforge.net/)
# from file : AppClass.sm

import statemap


class AppClassState(statemap.State):

    def Entry(self, fsm):
        pass

    def Exit(self, fsm):
        pass

    def Colon(self, fsm):
        self.Default(fsm)

    def Dig(self, fsm):
        self.Default(fsm)

    def EOF(self, fsm):
        self.Default(fsm)

    def EOS(self, fsm):
        self.Default(fsm)

    def Lett(self, fsm):
        self.Default(fsm)

    def Sep(self, fsm):
        self.Default(fsm)

    def Space(self, fsm):
        self.Default(fsm)

    def Unknown(self, fsm):
        self.Default(fsm)

    def Default(self, fsm):
        msg = "\n\tState: %s\n\tTransition: %s" % (
            fsm.getState().getName(), fsm.getTransition())
        raise statemap.TransitionUndefinedException(msg)

class Map1_Default(AppClassState):

    def EOF(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.makeStatistic()
        finally:
            fsm.setState(Map1.EOF)
            fsm.getState().Entry(fsm)

class Map1_Start(Map1_Default):

    def Colon(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def Dig(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.stringIsNotCorrect()
        finally:
            fsm.setState(Map1.Start)
            fsm.getState().Entry(fsm)

    def Lett(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Target)
            fsm.getState().Entry(fsm)

    def Sep(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Target)
            fsm.getState().Entry(fsm)

    def Space(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Start)
        fsm.getState().Entry(fsm)

    def Unknown(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

class Map1_Target(Map1_Default):

    def Colon(self, fsm):
        ctxt = fsm.getOwner()
        if ctxt.isTargetUnique() :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.addTarget()
                ctxt.clearBuff()
            finally:
                fsm.setState(Map1.Req1)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.deleteTarget()
                ctxt.clearBuff()
            finally:
                fsm.setState(Map1.Error)
                fsm.getState().Entry(fsm)


    def Dig(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Target)
            fsm.getState().Entry(fsm)

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.clearBuff()
            ctxt.stringIsNotCorrect()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

    def Lett(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Target)
            fsm.getState().Entry(fsm)

    def Sep(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Target)
            fsm.getState().Entry(fsm)

    def Space(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.clearBuff()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

    def Unknown(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

class Map1_Req1(Map1_Default):

    def Colon(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.deleteTarget()
            ctxt.clearBuff()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

    def Dig(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.deleteTarget()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

    def EOF(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addNewReq()
            ctxt.clearBuff()
            ctxt.clearReq()
            ctxt.makeStatistic()
            ctxt.stringIsCorrect()
        finally:
            fsm.setState(Map1.Start)
            fsm.getState().Entry(fsm)

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.clearBuff()
            ctxt.clearReq()
            ctxt.addNewReq()
            ctxt.stringIsCorrect()
        finally:
            fsm.setState(Map1.Start)
            fsm.getState().Entry(fsm)

    def Lett(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Req2)
            fsm.getState().Entry(fsm)

    def Sep(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Req2)
            fsm.getState().Entry(fsm)

    def Space(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Req1)
        fsm.getState().Entry(fsm)

    def Unknown(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.deleteTarget()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

class Map1_Req2(Map1_Default):

    def Colon(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.deleteTarget()
            ctxt.clearBuff()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

    def Dig(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Req2)
            fsm.getState().Entry(fsm)

    def EOF(self, fsm):
        ctxt = fsm.getOwner()
        if ctxt.isReqUnique() :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.addNewReq()
                ctxt.clearBuff()
                ctxt.clearReq()
                ctxt.makeStatistic()
                ctxt.stringIsCorrect()
            finally:
                fsm.setState(Map1.Start)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.deleteTarget()
                ctxt.clearBuff()
                ctxt.clearReq()
                ctxt.stringIsNotCorrect()
            finally:
                fsm.setState(Map1.Start)
                fsm.getState().Entry(fsm)


    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        if ctxt.isReqUnique() :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.addNewReq()
                ctxt.clearBuff()
                ctxt.clearReq()
                ctxt.stringIsCorrect()
            finally:
                fsm.setState(Map1.Start)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.deleteTarget()
                ctxt.clearBuff()
                ctxt.clearReq()
                ctxt.stringIsNotCorrect()
            finally:
                fsm.setState(Map1.Start)
                fsm.getState().Entry(fsm)


    def Lett(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Req2)
            fsm.getState().Entry(fsm)

    def Sep(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.addToBuff()
        finally:
            fsm.setState(Map1.Req2)
            fsm.getState().Entry(fsm)

    def Space(self, fsm):
        ctxt = fsm.getOwner()
        if ctxt.isReqUnique() :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.clearBuff()
            finally:
                fsm.setState(Map1.Req1)
                fsm.getState().Entry(fsm)
        else:
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.deleteTarget()
                ctxt.clearBuff()
            finally:
                fsm.setState(Map1.Error)
                fsm.getState().Entry(fsm)


    def Unknown(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.deleteTarget()
            ctxt.clearBuff()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)

class Map1_Error(Map1_Default):

    def Entry(self, fsm):
        ctxt = fsm.getOwner()
        ctxt.whyImHere()
        ctxt.clearReq()

    def Colon(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def Dig(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.clearBuff()
            ctxt.stringIsNotCorrect()
        finally:
            fsm.setState(Map1.Start)
            fsm.getState().Entry(fsm)

    def Lett(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def Sep(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def Space(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

    def Unknown(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)

class Map1_EOF(Map1_Default):
    pass

class Map1(object):

    Start = Map1_Start('Map1.Start', 0)
    Target = Map1_Target('Map1.Target', 1)
    Req1 = Map1_Req1('Map1.Req1', 2)
    Req2 = Map1_Req2('Map1.Req2', 3)
    Error = Map1_Error('Map1.Error', 4)
    EOF = Map1_EOF('Map1.EOF', 5)
    Default = Map1_Default('Map1.Default', -1)

class AppClass_sm(statemap.FSMContext):

    def __init__(self, owner):
        statemap.FSMContext.__init__(self, Map1.Start)
        self._owner = owner

    def __getattr__(self, attrib):
        def trans_sm(*arglist):
            self._transition = attrib
            getattr(self.getState(), attrib)(self, *arglist)
            self._transition = None
        return trans_sm

    def enterStartState(self):
        self._state.Entry(self)

    def getOwner(self):
        return self._owner

# Local variables:
#  buffer-read-only: t
# End:
